# 较小的font_size将使文本看起来像blured/prydown
font_size:
  min: 24
  max: 33

# 选择文本颜色范围
# 颜色边界是R,G,B格式
font_color:
  enable: true
  red:
    fraction: 1.0
    l_boundary: [200,55,55]
    h_boundary: [255,60,60]
#   blue:
#     fraction: 0
#     l_boundary: [0,0,150]
#     h_boundary: [255,55,55]
#   brown:
#     fraction: 0
#     l_boundary: [139,70,19]
#     h_boundary: [160,82,43]

#默认情况下，文本是由Pillow with绘制的 (https://stackoverflow.com/questions/43828955/measuring-width-of-text-python-pil)
# 如果“random_space”被启用，那么一些文本将被一个字符一个字符地绘制，并带有一个随机空间
random_space:
  enable: true
  fraction: 0.3
  min: -0.1 # -0.1将使字符非常接近，甚至重叠
  max: 0.1

# Do 重新映射 with sin()
# 目前这个过程非常缓慢!
curve:
  enable: false
  fraction: 0.3
  period: 360  # degree, sin 函数的周期
  min: 1 # sin 函数的幅值范围
  max: 5

# 随机裁剪文本高度
crop:
  enable: false
  fraction: 0.5

  # 顶部和底部将平等地应用
  top:
    min: 5
    max: 10 # 在像素中，这个值应该小于img_height
  bottom:
    min: 5
    max: 10 # 在像素中，这个值应该小于img_height

# 使用bg_dir中的图像作为文本的背景
img_bg:
  enable: true
  fraction: 0.5

# 文本的边框，应用random_space时不工作
text_border:
  enable: false
  fraction: 0.5

  # 比文字颜色浅
  light:
    enable: true
    fraction: 0.5

  #比文字颜色深
  dark:
    enable: true
    fraction: 0.5

# https://docs.opencv.org/3.4/df/da0/group__photo__clone.html#ga2bf426e4c93a6b1f21705513dfeca49d
# https://www.cs.virginia.edu/~connelly/class/2014/comp_photo/proj2/poisson.pdf
# 使用opencv seamlessClone()在背景上绘制文本
# 对于一些背景图像，这将使文本图像看起来更真实
seamless_clone:
  enable: false
  fraction: 0.5

#透视变换
perspective_transform:
  max_x: 25
  max_y: 25
  max_z: 3

#模糊
blur:
  enable: true
  fraction: 0.03

# 如果一个图像被应用模糊，它将不会被应用prydown
prydown:
  enable: true
  fraction: 0.03
  max_scale: 1.5 # 图像将首先调整到1.5倍，然后再调整到1x

#噪音
noise:
  enable: true
  fraction: 0.3
  gauss:
    enable: true
    fraction: 0.25

  uniform:
    enable: true
    fraction: 0.25

  salt_pepper:
    enable: true
    fraction: 0.25

  poisson:
    enable: true
    fraction: 0.25
#线条
line:
  enable: false
  fraction: 0.05

  under_line:
    enable: false
    fraction: 0.2

  table_line:
    enable: false
    fraction: 0.3

  middle_line:
    enable: false
    fraction: 0.5
#线的颜色
line_color:
  enable: false
  black:
    fraction: 0.5
    l_boundary: 0,0,0
    h_boundary: 64,64,64
  blue:
    fraction: 0.5
    l_boundary: [0,0,150]
    h_boundary: [60,60,255]

# 这些操作应用于最终的输出图像，
#因此，它也可以作为一种数据扩充方法应用于训练过程中。

# 默认情况下，文字比背景颜色深。
# 如果设置了‘reverse_color’，有些图片的背景颜色会比较深，文字颜色会比较浅
#相反的颜色
reverse_color:
  enable: false
  fraction: 0.5
#浮雕
emboss:
  enable: false
  fraction: 0.1
#锐化
sharp:
  enable: false
  fraction: 0.1

